version: "3"

services:
  postgres:
    image: postgres:9.6.0
    environment:
      POSTGRES_USER: yingxuan_devs
      POSTGRES_DB: myapp
      POSTGRES_PASSWORD: yingxuanApp
    volumes:
      - db-data:/var/lib/postgresql

  redis:
    image: redis:3.0.5
    volumes:
      - db-data:/var/lib/redis

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

volumes:
  db-data: