postgres:
  image: postgres:9.6.0
  environment:
    POSTGRES_USER: yingxuan_devs
    POSTGRES_PASSWORD: yingxuanApp
  ports:
    - '5432:5432'
  volumes:
    # You need to modify this to a local valid path.
    - ~/projects/docker-data/postresql:/var/lib/postgresql

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - ~/projects/docker-data/redis:/var/lib/redis

app:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C 'config/puma.rb'"
  links:
    - postgres
    - redis
  volumes:
    - .:/app
  ports:
    - '3000:3000'

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/app